#+TITLE: Lab 2: Information State Update (ISU)

* Preparations
- Create [[https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging][a new branch]] and call it ~lab-2~.
- You will work with ~/sisu/~ subfolder, it can run both as a backend
  app (for tests) and as a frontend (as a speechstate app).
- Follow the prerequisites in SISU's README. After this, if everything
  works as expected, your development environment should be ready for
  doing the lab.

SISU contains a partial implementation of IBiS1, and a simple domain. To understand what the system can do, see the automated tests in ~test/dme.test.js~.

* Task 1: Make system answer depend on day
Extend the implementation so that instead of asking the "Which course?" question, the system asks "Which day?". The system then should ask "Which course?" and provide information according to the table below:

| Course             | Day      | Room |
|--------------------+----------+------|
| Dialogue systems 2 | Friday   | G212 |
| Dialogue systems 2 | Thursday | J440 |
| Dialogue systems 2 | Tuesday  | J440 |

You will need to start with writing two failing automated tests (in ~test/dme.test.ts~).

This task involves modifying/extending the domain (in ~src/is.ts~) as
well as NLU and NLG (in ~src/nlug.ts~).

* Task 2a: Negative semantic understanding feedback
Extend the implementation so that when the user utters something that is not understood by the NLU, the system utters "Sorry, I don't understand."

This task involves modifying/extending domain-independent parts of the implementation, e.g. update rules (in ~src/rules.ts~). Specifically, you will need to come up with a new kind of move that conveys negative semantic understanding, and ensure that such a move gets added to next_moves when the NLU fails to parse the user's utterance. You will also need to ensure that the new kind of move can ge generated by the NLG.

Note that when the NLU does not understand an utterance, it returns an empty array. To check whether some variable ~x~ is an empty array, you can do ~if(Array.isArray(x) && x.length === 0) { ... }~.

Feel free to let your solution be informed by Larsson (2002, section 3.6.5 and rule 3.12). But you can also design your own solution.

* Task 2b: Feedback followed by repeated question
Ensure that when the system gives negative semantic understanding feedback, and previously asked a question from the plan, it asks the question again, e.g. like this:

- S: Hello! You can ask me anything!
- U: bla bla
- S: Sorry, I didn't understand.
- U: Where is the lecture?
- S: Which course?
- U: bla bla
- S: Sorry, I didn't understand. Which course?

Depending on how you solved 2a, this might already work.

* Task 2c: Final result
Ensure that the system provides the room information after several repeated questions. You will need to add another test case to ensure that.

* VG part
Choose one or two additional tasks to get 1 or 2 VG points.


** VG-A (1 bonus point)

Add new rule to SISU (and/or modify existing SISU rules) to support
other grounding strategies in addition to the negative semantic
understanding feedback according to Larsson (2002, section 3). For
instance, implement:
- negative contact feedback, or
- the support for different ways of grounding depending on ASR
  confidence scores

As before, start with a test case covering the desired system behaviour.

** VG-B (1 bonus point)

In SISU, the NLU is very primitive. But you can use Qdrant to make it more advanced. Implement a proof-of-concept version of it. Basically, now you are mapping utterance strings (e.g., "where is the lecture?") to something like:

#+begin_src json
  {
    "type": "ask",
    "content": { "type": "whq", "predicate": "booking_room" }
  }
#+end_src

You can make it into a [[https://qdrant.tech/documentation/manage-data/payload/][payload]] and retrieve it using RAG querying.


* Troubleshooting using logs
Logs can be very useful when troubleshooting the implementation. If you test live in the browser, you can look at the console in the web developer tools. In automated testing (~yarn test~), log entries are printed to the terminal; you can also pipe them to a file with ~yarn test 2>&1 > test.log~. Feel free to add your own log entries in your code, with ~console.log(...)~.

* Submission
Report the lab by submitting a link to a *new* pull request containing your solutions, including automated tests (in ~test/dme.test.ts~).
